name: bss-repo-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - pyyaml
  - openpyxl
  - pip
  - pip:
      - "numpy<2.0"
      - "scipy<1.14"
      - "peewee<4"
      - "xarray>=2024.10.0"
      - bw2data==4.5.3
      - bw2calc==2.2.2
      - bw2io==0.9.11
      - premise==2.3.2
