name: bss-repo-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - pyyaml
  - openpyxl
  - pip
  - pip:
      - "numpy==1.26.4"
      - "scipy==1.13.1"
      - "pandas==2.2.3"
      - "xarray==2024.2.0"
      - "peewee<4"
      - bw2data==4.5.3
      - bw2calc==2.2.2
      - bw2io==0.9.11
      - premise==2.3.2
